### ISSUE TITLE
Add go.mod

### ISSUE THREAD

**Issue by 89z** [amwolff/gorder#1]
Otherwise error is emitted:

~~~
PS C:\gorder> go build
go: go.mod file not found in current directory or any parent directory; see 'go
help modules'
~~~

can do it like this:

~~~
go mod init github.com/amwolff/gorder
~~~

**Comment by amwolff** [comment]
Hi Steven,

Thanks a lot for creating the issue. Do you mind creating a Go module for this package?

**Comment by 89z** [comment]
https://github.com/amwolff/gorder/pull/2

**Comment by 89z** [comment]
Cmon dude, its not that hard.
